### PR TITLE
Add gausslaguerre tests to resolve #39

### LINKED ISSUE #39: Better line coverage testing in gausslaguerre
@popsomer, can you add tests that execute lines in `gausslaguerre` for `alpha>1`, `asyRHgen`, `polyAsyRHgen`, `asyBesselgen`, `asyAirygen`, etc ?

### PR DESCRIPTION
**Pull request by popsomer**
More tests were added as suggested in #39 to test the functions in gausslaguerre.jl for some inputs. The cause of #38 was the usage of `zeros(mn,1)`, which is now corrected to `zeros(mn)`. Some errors were found and corrected, which will also be suggested to chebfun. More explicit expressions for higher order terms were added to increase accuracy for 128<n<900. Apart from being lengthy, a possible remaining problem is that not all integers in them are representable as Int64, possibly leading to the slightly higher error on `UQ[1,2,4,5,3].` When running `julia test/runtests.jl` in the terminal, I do get a "test failed: 0.03816691590382637 < 1.0e-14" from test_gaussjacobi.jl on line 59.

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
Thanks, @popsomer!  

Your `include`s in `test_gausslaguerre` are causing problems for Travis CI.  It is probably better to import the function using `import gausslaguerre.functionName` or by explicitly specify it within your test script with `@test gausslaguerre.functionName( arguments )`.

**Comment by ajt60gaibb** [comment]
The tests in master pass for me on Julia versions `0.3`, `0.4`, `0.4.6`, and `nightly` for both Linux and Mac.  Are you using something different than those options?  If not, then I am unable to reproduce the test failure you are observing in `test_gaussjacobi`.

**Comment by popsomer** [comment]
I'm using Julia version 0.4.7-pre+1 on Linux (Ubuntu 14.04 LTS).

**Comment by ajt60gaibb** [comment]
Now we have 
```
ERROR: `factorial` has no method matching factorial(::Float64)
 in getV at /home/travis/.julia/v0.3/FastGaussQuadrature/src/gausslaguerre.jl:1439
 in getUQ at /home/travis/.julia/v0.3/FastGaussQuadrature/src/gausslaguerre.jl:1495
 in asyRHgen at /home/travis/.julia/v0.3/FastGaussQuadrature/src/gausslaguerre.jl:1106
 in gausslaguerre at /home/travis/.julia/v0.3/FastGaussQuadrature/src/gausslaguerre.jl:17
```
There are possibly other things: see `https://travis-ci.org/ajt60gaibb/FastGaussQuadrature.jl`.

**Comment by popsomer** [comment]
The errors I get from those four Julia versions seem to be higher than the ones I got: I wonder whether it is reasonable to increase each of the tolerances until the tests pass? 

From the Julia:nightly, I got `LoadError: ArgumentError: gausslaguerre not found in path.` (Job 20.4) when using `import gausslaguerre.getUQ` and `LoadError: type #gausslaguerre has no field getUQ` when using `UQ = gausslaguerre.getUQ(alpha, 1.0, 1, T+1)` (Job 24.4).

**Comment by ajt60gaibb** [comment]
What would you need to increase those tolerances to? 

Oh, perhaps the Julia team are changing `import gausslaguerre.getUQ` for v0.5.

**Comment by popsomer** [comment]
From 3e-13 to about 2e-11 for integration and to about 3e-9 for node 37 at n=251, so far...

The ArgumentError also appeared when using `import` in older Julia versions

**Comment by ajt60gaibb** [comment]
I would like a better accuracy in the nodes than `3e-9`. Possible? I do not want to give up this many digits, if possible.

**Comment by ajt60gaibb** [comment]
Do you know how to export a subfunction for unit testing, but not export it globally? 

Maybe it's just this `gausslaguerre.getUQ()`?

**Comment by dlfivefifty** [comment]
What’s a subfunction?

**Comment by dlfivefifty** [comment]
Also, factorial(::Float64) is fine:

```julia
julia> factorial(1.0)
1.0
```

**Comment by dlfivefifty** [comment]
I think you probably mean 

```
import FastGaussQuadrature.getUQ
```

**Comment by ajt60gaibb** [comment]
It seems that `factorial(::Float64)` is not fine in Julia version `0.3`.

**Comment by dlfivefifty** [comment]
> not all integers in them are representable as Int64

Why not use BigInt?

```julia
Float64(parse(BigInt,"12343567543253543454334543453")/parse(BigInt,"123435675432535434543345434543553"))
```

**Comment by ajt60gaibb** [comment]
Yes, thank you for `FastGaussQuadrature.getUQ`.

**Comment by popsomer** [comment]
@dlfivefifty Fortunately, Julia automatically uses the type in which the integer fits: it switches to Int128 for the large integers in the explicit expressions, or indeed BigInt for even larger ones. I guess I was just looking for explanations for the slightly higher error on `UQ[1,2,4,5,3]`, but it seems it is not integer overflow after all.

**Comment by popsomer** [comment]
Thanks for suggesting `import FastGaussQuadrature.getUQ`: now the subfunction can be found. The Travic CI thinks the problem with Julia: nightly is because of a stalled build or because of something wrong with the build itself.

I had `sum(g[1,1:n,1]*f[(n+2):-1:3,1])/f[2,1]` in my 0.4.7-pre+1, which gave problems with Julia:nightly in Job 19.4. So I tried `sum(g[1,1:n,1].*f[(n+1):-1:2,1])/f[1,1]`, which gave the lower accuracy I reported. However, `sum(reshape(g[1,1:n,1],(n,1)).*reshape(f[(n+2):-1:3,1],(n,1) ) )/f[2,1]` recovered the accuracy I had.

**Comment by ajt60gaibb** [comment]
I reran Travis CI. Sometimes Travis CI just does not build correctly. A rerun usually works. 

Now, it looks like there is a dimension mismatch on `line 89` in `test_gausslaguerre` on Julia: nightly.  Care to fix it, then we are done. 👍 
https://travis-ci.org/ajt60gaibb/FastGaussQuadrature.jl/builds/151449714

(This package has relatively simple programming logic so I think line coverage is an OK measure at quality of the unit tests. I agree, though. Line coverage is a misleading measure for some packages.)

**Comment by ajt60gaibb** [comment]
If you cannot fix it with a quick effort, then I will turn off the Julia: nightly check in Travis CI.  We can make the package work in Julia 0.5 once it stops randomly breaking things.

**Comment by ajt60gaibb** [comment]
Close #39

**Pull request merged**
