### PR TITLE
WIP: Optimizations

### PR DESCRIPTION
**Pull request by yuyichao**
This is WIP but could be merged at any time.

I have just implemented the ones that are relatively easy to do and this is not remotely closed to what julia can easily achive.

Speed up of `gaussjacobi` for the parameters in the test range from 10% (for the cases I basically haven't touch much yet) to `10x` (for `gaussjacobi(42, -.1, .3)` because of the reduction of allocations).

### CODE REVIEW

**Comment by ajt60gaibb** [comment]
Thanks!

**Comment by dlfivefifty** [comment]
Hi Yuyichao,

I think this actually broke gausslegendre.  Unfortunately there were no unit tests that checked the quadrature scheme worked.  I've just added a few very simple tests. If I get a chance, I'll see if I can track down the error.

**Comment by dlfivefifty** [comment]
PS At least the timings are a lot better!  gausslegendre is 20x faster.

**Comment by dlfivefifty** [comment]
OK I've added a basic quadrature test for all routines, the only one that fails is gausslegendre.  I'll step through your changes to see if I can track it down.

**Comment by dlfivefifty** [comment]
Fixed!  There were actually two different errors: a typo in besselJ1 which broke large n, and rec(n) rearrangement was wrong.

**Pull request merged**
